<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    table,
    th,
    td {
        border-collapse: collapse;
    }

    th,
    td {
        padding: 10px;
    }

    th {
        background-color: #04AA6D;
        color: white;
    }
    }
</style>

<body>
    <div>
        <h2>Orders</h2>
        <table>
            <tr>
                <th>Customer Name</th>
                <th>Product Name</th>
                <th>Product Quantity</th>
                <th>Order Status</th>
            </tr>
            <tbody>
                <?php
                $html = "";
                foreach ($orders as $v) {
                    $html .= "<tr>
                    <td>" . $v->customer_name . "</td>
                    <td>" . $v->product_name . "</td>
                    <td>" . $v->product_quantity . "</td>
                    <td>" . $v->status . "</td>
                    </tr>";
                }
                echo $html;
                ?>
            </tbody>
        </table>
    </div>
</body>

</html>