<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

</head>

<body>
    <div class="container">
        <h2 class="mt-4">Dashboard</h2>

        <a href="/app/product/addproduct">
            <input type="submit" name="addproduct" value="Add Products" class="btn btn-success mt-2">
        </a>
        <br>
        <a href="/app/product/index">
            <input type="submit" name="products" value="View Products" class="btn btn-warning mt-2">
        </a>
        <br>
        <a href="/app/orders/index">
            <input type="submit" name="orders" value="View Orders" class="btn btn-info mt-2">
        </a>
        <br>
        <a href="/app/login/index">
            <input type="submit" name="logout" value="Logout!!" class="btn btn-danger mt-2">
        </a>
    </div>
</body>

</html>