<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

</head>
<style>
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    table,
    th,
    td {
        border-collapse: collapse;
    }

    th,
    td {
        padding: 10px;
    }

    th {
        background-color: #04AA6D;
        color: white;
    }
</style>

<body>
    <div class="container-fluid">
        <div class="">
            <h2>Products</h2>
            <table>
                <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Product Price</th>
                    <th>Product Stock</th>
                    <th>Order Product</th>
                </tr>
                <tbody>
                    <?php
                    foreach ($products as $v) { ?>
                        <tr>
                            <form action="/frontend/products/placeorderui" method="POST">
                            <td><?php echo $v->id ?></td>
                            <td><?php echo $v->name ?></td>
                            <td><?php echo $v->price ?></td>
                            <td><?php echo $v->stock ?></td>
                            <td><input type="submit" name="order" value="Place Order" class="btn btn-warning"></td>
                            <td><input type="hidden" name="id" value="<?php echo $v->id ?>"></td>
                            </form>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>

        <a href="/frontend/login/index">
            <input type="submit" name="logout" value="Logout" class="btn btn-danger mt-3">
        </a>
    </div>
</body>

</html>