<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

</head>

<body>
    <h2>Place Order</h2>
    <form action="/frontend/products/placeorder" method="POST">

        <label for="customer_name">Customer Name: </label>
        <input type="text" name="customer_name"><br>

        <label for="product_name">Product Name: </label>
        <input type="text" name="product_name"><br>

        <label for="quantity">Product Quantity: </label>
        <input type="text" name="quantity"><br>

        <input type="hidden" name="product_id" value="<?php echo $product_id; ?>">

        <input type="submit" name="order" value="Place Order" class="btn btn-success">

    </form>
</body>

</html>