<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<style>
    input[type=text] {
        width: 20%;
    }
</style>

<body>
    <div class="row">

        <form action="/app/product/addproduct" method="POST">
            <div class="col text-center">

                <h2 class="text-center">Add Product</h2><br>

                <label for="name">Product Name: </label><br>
                <input type="text" name="name"><br>

                <label for="price">Product price: </label><br>
                <input type="text" name="price"><br>

                <label for="stock">Product stock: </label><br>
                <input type="text" name="stock"><br>

                <input type="submit" name="addproduct" value="Add Product" class="btn btn-danger mt-2"><br>



            </div>
        </form>

        <div class="col text-center">
            <a href="/app/admin/index"><input type="submit" name="back" value="Go back" class="btn btn-warning mt-2"></a><br>
            <?php if (isset($addproductmsg)) {
                echo $addproductmsg;
            } ?>
        </div>
    </div>

</body>

</html>